spring:
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: film-service
          uri: lb://FILM-SERVICE
          predicates:
            - Path=/api/v1/person/**,/api/v1/film/**,/api/v1/age-limit/**,/api/v1/country/**,/api/v1/genre/**,/api/v1/person/**
          filters:
            - name: JwtForwardingFilter
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user/**,/api/v1/role/**,/api/v1/auth/**
          filters:
            - name: JwtForwardingFilter

server:
  port: 8222