server:
  port: 8083

management:
  observations:
    feign:
      enabled=false:

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/reviews
    username: nikita
    password: nikita
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

application:
  config:
    urls:
      genre-url: http://localhost:8222/api/v1/genre
      age-limit-url: http://localhost:8222/api/v1/age-limit
      country-url: http://localhost:8222/api/v1/country
      film-url: http://localhost:8222/api/v1/film
      person-url: http://localhost:8222/api/v1/person
      user-url: http://localhost:8222/api/v1/user
      auth-url: http://localhost:8222/api/v1/auth
      role-url: http://localhost:8222/api/v1/role