services:
  postgres-db-users:
    container_name: db-users
    image: postgres
    environment:
      POSTGRES_USER: nikita
      POSTGRES_PASSWORD: nikita
      POSTGRES_DB: users
    ports:
      - "5433:5432"
    networks:
      - microservices-net
    restart: unless-stopped

  postgres-db-films:
    container_name: db-films
    image: postgres
    environment:
      POSTGRES_DB: films
      POSTGRES_USER: nikita
      POSTGRES_PASSWORD: nikita
    ports:
      - "5434:5432"
    networks:
      - microservices-net
    restart: unless-stopped

  postgres-db-reviews:
    container_name: db-reviews
    image: postgres
    environment:
      POSTGRES_DB: reviews
      POSTGRES_USER: nikita
      POSTGRES_PASSWORD: nikita
    ports:
      - "5435:5432"
    networks:
      - microservices-net
    restart: unless-stopped

  kafka:
    container_name: kafka
    image: apache/kafka
    ports:
      - "9092:9092"
    restart: unless-stopped


networks:
  microservices-net:
    driver: bridge